# 100 numpy exercises



#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(f'numpy version = {np.__version__}')

numpy version = 1.23.4


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
ex3 = np.zeros((10))
ex3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [8]:
print(ex3.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
ex6 = np.zeros(9)
ex6 = np.insert(arr=ex6, values=1, obj=(4))
ex6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
ex7 = np.arange(10,50)
ex7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
ex8 = np.flip(ex7)
ex8

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
ex9 = np.arange(0,9).reshape(3,3)
ex9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [31]:
ex10 = np.array([1,2,0,0,4,0])
result = np.where(ex10 == 0)
result


(array([2, 3, 5], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
ex11 = np.identity(3)
ex11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [36]:
ex12 = np.random.rand(3,3,3)
ex12

array([[[0.25770803, 0.35828211, 0.90814837],
        [0.08728499, 0.73610239, 0.32114999],
        [0.88528763, 0.23766912, 0.27845362]],

       [[0.94510185, 0.31409855, 0.08257454],
        [0.56652989, 0.03090334, 0.80645373],
        [0.824382  , 0.73985247, 0.90121073]],

       [[0.08469699, 0.93794564, 0.02085482],
        [0.81109059, 0.15118709, 0.97418847],
        [0.93815928, 0.38112015, 0.23928191]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [37]:
ex13 = np.random.rand(10,10)
print(ex13)
print(ex13.min())
print(ex13.max())

[[0.06258234 0.28782769 0.71746967 0.27405525 0.93262259 0.31084431
  0.70341328 0.10886188 0.26173539 0.43781404]
 [0.92871584 0.86305904 0.24405106 0.95319131 0.67799731 0.40145459
  0.57966065 0.37986454 0.74509884 0.21073267]
 [0.29664564 0.57687132 0.65388939 0.05863246 0.58196792 0.80988559
  0.61876705 0.88629797 0.7290019  0.97122897]
 [0.6877345  0.40643643 0.57805801 0.69494576 0.23308837 0.96203292
  0.00384794 0.48336547 0.58827267 0.7301997 ]
 [0.90269692 0.76815423 0.46808557 0.01810642 0.88102126 0.11334938
  0.97418858 0.99259746 0.74122889 0.77511357]
 [0.75009027 0.21679531 0.68915573 0.38531932 0.88573641 0.95662268
  0.63657767 0.34329298 0.29972883 0.49786152]
 [0.40943706 0.30377203 0.29877585 0.21522452 0.08303243 0.91974064
  0.50789545 0.80757214 0.78222353 0.07569372]
 [0.53670347 0.75632593 0.21158671 0.78954659 0.12841238 0.3118866
  0.76356246 0.08593168 0.30992383 0.63677612]
 [0.72296039 0.25556939 0.32580428 0.28715575 0.38463648 0.01310117
  0.82301856 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
ex14 = np.random.rand(30)
print(ex14)
print(ex14.mean())

[0.0420036  0.86943017 0.02644888 0.20455873 0.23181615 0.25027084
 0.60771191 0.92617451 0.40137101 0.59697685 0.19996924 0.39155121
 0.95792065 0.34415231 0.64806244 0.18271997 0.31702455 0.3101529
 0.33074221 0.60256831 0.8941993  0.35652032 0.44536617 0.77821783
 0.92198832 0.23874752 0.88546108 0.17284884 0.40777643 0.33082159]
0.4624524607816163


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [41]:
ex15 = np.ones((10,10))
ex15[1:-1,1:-1] = 0
ex15

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [45]:
ex16 = np.random.rand(5,5)
ex16[0,:],ex16[:,-1], ex16[:,0], ex16[-1,:] = 0, 0, 0, 0
ex16

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.60966735, 0.0582897 , 0.99190635, 0.        ],
       [0.        , 0.90281565, 0.78696034, 0.2182111 , 0.        ],
       [0.        , 0.14918882, 0.65946386, 0.47096414, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [3]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [8]:
ex18 = np.diag(1+np.arange(4),k=-1)
print(ex18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [9]:
ex19 = np.zeros((8,8),dtype=int)
ex19[1::2,::2] = 1
ex19[::2,1::2] = 1
print(ex19)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [10]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [11]:
ex21 = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(ex21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [12]:
ex22 = np.random.random((5,5))
ex22 = (ex22 - np.mean (ex22)) / (np.std (ex22))
print(ex22)

[[ 0.87887442 -1.32315805  0.78452582 -0.38051012  1.00286166]
 [-0.76933523 -1.30178684 -0.92384179 -0.74028166 -1.28443929]
 [ 1.08604274 -1.29390187  2.01507997  0.40030377  0.71477044]
 [ 0.07561377  1.33774497  0.15169342  1.56293225 -0.60641143]
 [-0.44273081  0.63204356 -0.84409448  0.5236619  -1.25565711]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [13]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [14]:
ex24 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(ex24)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [16]:
ex25 = np.arange(11)
ex25[(3 < ex25) & (ex25 < 8)] *= -1
print(ex25)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [17]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [20]:
Z = np.random.randint(12)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

False

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [21]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\lengs\AppData\Local\Temp\ipykernel_7504\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\lengs\AppData\Local\Temp\ipykernel_7504\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [22]:
ex29 = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(ex29)), ex29))

[ 2. -6. -5. -1.  9. -1.  3.  2. -6. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [23]:
ex30_1 = np.random.randint(0,10,10)
ex30_2 = np.random.randint(0,10,10)
print(np.intersect1d(ex30_1,ex30_2))

[0 3 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [25]:
defaults = np.seterr(all="ignore")
ex31 = np.ones(10) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [26]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [27]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [30]:
ex34 = np.arange('2022-06', '2022-12', dtype='datetime64[D]')
print(ex34)

['2022-06-01' '2022-06-02' '2022-06-03' '2022-06-04' '2022-06-05'
 '2022-06-06' '2022-06-07' '2022-06-08' '2022-06-09' '2022-06-10'
 '2022-06-11' '2022-06-12' '2022-06-13' '2022-06-14' '2022-06-15'
 '2022-06-16' '2022-06-17' '2022-06-18' '2022-06-19' '2022-06-20'
 '2022-06-21' '2022-06-22' '2022-06-23' '2022-06-24' '2022-06-25'
 '2022-06-26' '2022-06-27' '2022-06-28' '2022-06-29' '2022-06-30'
 '2022-07-01' '2022-07-02' '2022-07-03' '2022-07-04' '2022-07-05'
 '2022-07-06' '2022-07-07' '2022-07-08' '2022-07-09' '2022-07-10'
 '2022-07-11' '2022-07-12' '2022-07-13' '2022-07-14' '2022-07-15'
 '2022-07-16' '2022-07-17' '2022-07-18' '2022-07-19' '2022-07-20'
 '2022-07-21' '2022-07-22' '2022-07-23' '2022-07-24' '2022-07-25'
 '2022-07-26' '2022-07-27' '2022-07-28' '2022-07-29' '2022-07-30'
 '2022-07-31' '2022-08-01' '2022-08-02' '2022-08-03' '2022-08-04'
 '2022-08-05' '2022-08-06' '2022-08-07' '2022-08-08' '2022-08-09'
 '2022-08-10' '2022-08-11' '2022-08-12' '2022-08-13' '2022-08-14'
 '2022-08-

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [31]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [4]:
ex36 = np.random.uniform(0,10,10)

print(ex36 - ex36%1)
print(ex36 // 1)
print(np.floor(ex36))
print(ex36.astype(int))
print(np.trunc(ex36))

[6. 1. 1. 2. 1. 9. 0. 3. 9. 9.]
[6. 1. 1. 2. 1. 9. 0. 3. 9. 9.]
[6. 1. 1. 2. 1. 9. 0. 3. 9. 9.]
[6 1 1 2 1 9 0 3 9 9]
[6. 1. 1. 2. 1. 9. 0. 3. 9. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [6]:
ex37 = np.zeros((5,5))
ex37 += np.arange(5)
print(ex37)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [8]:
def generate():
    for x in range(10):
        yield x
ex38 = np.fromiter(generate(),dtype=float,count=-1)
print(ex38)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [9]:
ex39 = np.linspace(0,1,11,endpoint=False)[1:]
print(ex39)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [10]:
ex40 = np.random.random(10)
ex40.sort()
print(ex40)

[0.29137519 0.30752275 0.34878596 0.35724197 0.37671916 0.51602456
 0.62770001 0.75626125 0.79908468 0.92817312]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [11]:
ex41 = np.arange(10)
np.add.reduce(ex41)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [12]:
ex421 = np.random.randint(2,5)
ex422 = np.random.randint(2,5)
equal = np.array_equal(ex421,ex422)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [13]:
ex43 = np.zeros(10)
ex43.flags.writeable = False
ex43[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [14]:
ex44 = np.random.random((10,2))
X,Y = ex44[:,0], ex44[:,1]
ex441 = np.sqrt(X**2+Y**2)
ex442 = np.arctan2(Y,X)
print(ex441)
print(ex442)

[0.18955422 0.66694455 1.06245199 0.82650188 0.69026683 0.48641212
 0.91151378 0.9538162  0.88672697 0.78175863]
[1.12827055 0.07750367 0.66080835 0.42437917 0.42072609 1.44115813
 0.83009155 0.03524263 0.87759067 0.94627804]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [16]:
ex45 = np.random.random(10)
ex45[ex45.argmax()] = 0
print(ex45)

[0.23363555 0.75766811 0.44846755 0.         0.34392227 0.69526886
 0.02480556 0.47713817 0.55230571 0.92404802]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [17]:
ex46 = np.zeros((5,5), [('x',float),('y',float)])
ex46['x'], ex46['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(ex46)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [18]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [19]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [20]:
np.set_printoptions(threshold=float("inf"))
ex49 = np.zeros((40,40))
print(ex49)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [21]:
ex50 = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(ex50-v)).argmin()
print(ex50[index])

17


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [22]:
ex51 = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(ex51)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\lengs\AppData\Local\Temp\ipykernel_2136\729923031.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ex51 = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [23]:
ex52 = np.random.random((10,2))
X,Y = np.atleast_2d(ex52[:,0], ex52[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.30224434 0.77892721 0.47004086 0.89326047 0.07881146
  0.16510168 0.42018641 0.48608984 0.66845184]
 [0.30224434 0.         0.90478775 0.70237096 0.79301157 0.37457198
  0.1681266  0.11952048 0.70146257 0.3675542 ]
 [0.77892721 0.90478775 0.         0.40328481 0.63091203 0.72959686
  0.89400855 0.95722577 0.35752732 1.1176692 ]
 [0.47004086 0.70237096 0.40328481 0.         0.84254651 0.39946918
  0.62333622 0.79515324 0.04902532 1.01652226]
 [0.89326047 0.79301157 0.63091203 0.84254651 0.         0.90031158
  0.89789089 0.75979027 0.79875933 0.7727399 ]
 [0.07881146 0.37457198 0.72959686 0.39946918 0.90031158 0.
  0.2439039  0.49041952 0.41950286 0.73761979]
 [0.16510168 0.1681266  0.89400855 0.62333622 0.89789089 0.2439039
  0.         0.28566521 0.63353755 0.53039977]
 [0.42018641 0.11952048 0.95722577 0.79515324 0.75979027 0.49041952
  0.28566521 0.         0.78910684 0.24840336]
 [0.48608984 0.70146257 0.35752732 0.04902532 0.79875933 0.41950286
  0.63353755 0.789106

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [24]:
ex53 = (np.random.rand(10)*100).astype(np.float32)
Y = ex53.view(np.int32)
Y[:] = ex53
print(Y)

[ 7 56 56 20 49 53 97 77 97 59]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [2]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
ex54 = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(ex54)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\lengs\AppData\Local\Temp\ipykernel_8052\430415611.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ex54 = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [3]:
ex55 = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(ex55):
    print(index, value)
for index in np.ndindex(ex55.shape):
    print(index, ex55[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [4]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
ex56 = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(ex56)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [5]:
n = 10
p = 3
ex57 = np.zeros((n,n))
np.put(ex57, np.random.choice(range(n*n), p, replace=False),1)
print(ex57)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [7]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-3.65272077e-01  5.31267966e-02 -2.42744818e-01  8.26183521e-02
  -4.16252961e-01  4.09818115e-01 -3.17375741e-01  3.11063672e-01
   2.42325951e-01  2.42692710e-01]
 [-2.48069280e-01 -1.16038853e-01 -1.19347218e-01 -4.90770121e-01
   4.68629394e-01 -2.37130810e-01  4.36304317e-01  3.52269759e-01
  -2.82918403e-01  2.37071214e-01]
 [-1.14771488e-01  6.03850386e-03  2.49952613e-01  1.38961507e-01
   2.89103286e-01  4.13500634e-01  3.15270363e-03 -4.60180434e-01
  -2.65583986e-01 -2.60173339e-01]
 [-2.02771073e-01  2.15503359e-02  1.78272176e-01  2.31167328e-04
  -1.82253906e-01  7.15477720e-02 -3.43803295e-01  1.81303567e-01
   4.71594174e-01 -1.95670919e-01]
 [ 2.15926834e-03 -1.76481244e-01  6.90906078e-02 -3.06938342e-01
  -1.62549314e-01  4.51865339e-01  9.48079006e-02 -2.64827291e-01
  -2.96473281e-01  5.89346356e-01]]


#### 59. How to sort an array by the nth column? (★★☆)

In [8]:
ex59 = np.random.randint(0,10,(3,3))
print(ex59)
print(ex59[ex59[:,1].argsort()])

[[6 1 4]
 [2 0 9]
 [3 1 7]]
[[2 0 9]
 [6 1 4]
 [3 1 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [9]:
ex60 = np.random.randint(0,3,(3,10))
print((~ex60.any(axis=0)).any())
ex60=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(ex60).all(axis=0))

True
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [10]:
ex610 = np.random.uniform(0,1,10)
ex611 = 0.5
m = ex610.flat[np.abs(ex610 - ex611).argmin()]
print(m)

0.5069025969263339


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [11]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [12]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

ex63 = NamedArray(np.arange(10), "range_10")
print (ex63.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [13]:
ex64 = np.ones(10)
I = np.random.randint(0,len(ex64),20)
ex64 += np.bincount(I, minlength=len(ex64))
print(ex64)
np.add.at(ex64, I, 1)
print(ex64)

[3. 2. 3. 3. 3. 3. 2. 1. 8. 2.]
[ 5.  3.  5.  5.  5.  5.  3.  1. 15.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [14]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
ex65 = np.bincount(I,X)
print(ex65)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [15]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [16]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[34 51 54 43]
 [53 45 58 38]
 [61 61 77 64]]
[[34 51 54 43]
 [53 45 58 38]
 [61 61 77 64]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [17]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.60755333 0.5777765  0.54826508 0.60597841 0.46249507 0.42330155
 0.59250136 0.59983448 0.5725458  0.28221303]


#### 69. How to get the diagonal of a dot product? (★★★)

In [19]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.69331897, 0.77928505, 0.80716025, 1.96068243, 1.36696326])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [20]:
ex70 = np.array([1,2,3,4,5])
nz = 3
ex700 = np.zeros(len(ex70) + (len(ex70)-1)*(nz))
ex700[::nz+1] = ex70
print(ex700)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [21]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [22]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [23]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 54) ( 4, 61) ( 5,  6) ( 5, 53) ( 6, 15) ( 6, 53) ( 6, 75) ( 8, 26)
 ( 8, 96) (15, 75) (17, 60) (17, 63) (26, 96) (34, 73) (34, 83) (35, 53)
 (35, 96) (37, 64) (37, 81) (41, 71) (41, 76) (53, 96) (54, 61) (60, 63)
 (64, 81) (71, 76) (73, 83) (74, 85) (74, 90) (85, 90)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [24]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [25]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
ex75 = np.arange(20)
print(moving_average(ex75, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [29]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
ex76 = rolling(np.arange(10), 3)
print(ex76)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [30]:
ex77 = np.random.randint(0,2,100)
np.logical_not(ex77, out=ex77)

ex77 = np.random.uniform(-1.0,1.0,100)
np.negative(ex77, out=ex77)

array([ 0.45122637, -0.62780909,  0.38448127,  0.28150851, -0.28532261,
       -0.5349975 ,  0.69090684,  0.37802495, -0.12082011, -0.21960688,
       -0.38437174,  0.00800663, -0.38026775,  0.03822034,  0.5285848 ,
        0.55479828, -0.99087688,  0.4637877 , -0.38087273, -0.56502095,
        0.00469668,  0.9986766 , -0.8295079 , -0.17310474,  0.7700879 ,
        0.51003542,  0.68343829, -0.34629438, -0.11413084, -0.21315061,
        0.60968262, -0.69384358, -0.98425844,  0.12569264, -0.93905108,
       -0.19394661, -0.88406979,  0.92994874, -0.17086924,  0.40740755,
       -0.02988129,  0.56653339,  0.51850388,  0.07011751, -0.11867139,
       -0.36574127,  0.78653563,  0.26848725, -0.12494751,  0.97770404,
       -0.30072662,  0.09380391, -0.923025  ,  0.01025564,  0.96339848,
       -0.09296919,  0.91909825, -0.09646463, -0.28873105,  0.5545374 ,
       -0.5531719 ,  0.72665258,  0.18464317, -0.274833  ,  0.05723329,
       -0.43402578, -0.13747289, -0.35072622, -0.65692921,  0.06

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [31]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 0.19751634  9.42626183  0.67365148  2.08380814  9.500437    1.49056939
  3.43380523 13.63336098  7.97747785  6.53805656]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [32]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[4.53401537e+00 3.66349862e+00 1.56720413e+01 3.53442128e+00
  3.55118871e+00 1.88145775e+01 1.51803874e+00 6.16713599e+00
  1.14271574e+01 1.54139130e+01]
 [2.66730120e+00 2.20317707e+00 9.55880909e+00 2.12849338e+00
  4.68229329e-01 1.30463817e+01 4.61484011e+00 1.12854188e-03
  5.14113099e+00 1.21104463e+01]
 [4.43016539e+00 2.39190951e+00 3.64258507e+00 2.42831650e+00
  6.48852700e+00 6.85347397e+00 1.05017472e+01 5.82920184e+00
  7.41992967e-02 1.23160896e+01]
 [7.59816936e-01 9.66523896e-02 5.40448165e-01 1.13210061e-01
  6.90357127e+00 3.57585290e+00 1.47512019e+01 1.01984864e+01
  5.34133931e+00 6.32580367e+00]
 [6.04963486e+00 3.82923355e+00 2.46350096e+00 3.88182612e+00
  5.36121701e+00 2.56578666e+00 1.67441088e+01 1.23185921e+01
  8.65797950e+00 8.03737649e-01]
 [5.51136977e+00 8.51498218e+00 7.64370874e+00 8.48789770e+00
  2.80501714e+00 1.25384143e+01 6.63891736e+00 2.22190219e+00
  1.00927401e+00 3.83648229e+00]
 [1.95542629e+00 4.81981191e+00 1.34370109e+01 4.71825149e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [40]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

print(Z)
print(R)

[[0 4 9 0 6 1 5 6 9 6]
 [9 7 7 6 3 3 1 0 9 9]
 [2 5 1 7 9 9 6 6 2 4]
 [7 4 0 5 1 1 5 4 3 0]
 [4 8 3 2 5 6 9 5 6 0]
 [8 5 8 2 8 6 3 6 8 2]
 [7 6 5 8 8 9 3 9 6 8]
 [2 3 9 8 1 2 0 0 4 9]
 [9 7 6 0 1 2 3 8 5 9]
 [3 9 5 2 0 6 9 2 7 7]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [41]:
_ex81 = np.arange(1,15,dtype=np.uint32)
ex81 = stride_tricks.as_strided(_ex81,(11,4),(4,4))
print(ex81)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [42]:
ex82 = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(ex82) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [43]:
ex83 = np.random.randint(0,10,50)
print(np.bincount(ex83).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [44]:
ex84 = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (ex84.shape[0]-3)
j = 1 + (ex84.shape[1]-3)
C = stride_tricks.as_strided(ex84, shape=(i, j, n, n), strides=ex84.strides + ex84.strides)
print(C)

[[[[2 4 0]
   [0 1 2]
   [2 1 1]]

  [[4 0 2]
   [1 2 2]
   [1 1 1]]

  [[0 2 2]
   [2 2 4]
   [1 1 1]]

  [[2 2 0]
   [2 4 1]
   [1 1 4]]

  [[2 0 1]
   [4 1 1]
   [1 4 0]]

  [[0 1 1]
   [1 1 4]
   [4 0 0]]

  [[1 1 3]
   [1 4 3]
   [0 0 1]]

  [[1 3 4]
   [4 3 0]
   [0 1 0]]]


 [[[0 1 2]
   [2 1 1]
   [3 4 3]]

  [[1 2 2]
   [1 1 1]
   [4 3 3]]

  [[2 2 4]
   [1 1 1]
   [3 3 3]]

  [[2 4 1]
   [1 1 4]
   [3 3 1]]

  [[4 1 1]
   [1 4 0]
   [3 1 3]]

  [[1 1 4]
   [4 0 0]
   [1 3 3]]

  [[1 4 3]
   [0 0 1]
   [3 3 4]]

  [[4 3 0]
   [0 1 0]
   [3 4 0]]]


 [[[2 1 1]
   [3 4 3]
   [1 3 4]]

  [[1 1 1]
   [4 3 3]
   [3 4 4]]

  [[1 1 1]
   [3 3 3]
   [4 4 4]]

  [[1 1 4]
   [3 3 1]
   [4 4 3]]

  [[1 4 0]
   [3 1 3]
   [4 3 4]]

  [[4 0 0]
   [1 3 3]
   [3 4 3]]

  [[0 0 1]
   [3 3 4]
   [4 3 4]]

  [[0 1 0]
   [3 4 0]
   [3 4 3]]]


 [[[3 4 3]
   [1 3 4]
   [4 2 1]]

  [[4 3 3]
   [3 4 4]
   [2 1 0]]

  [[3 3 3]
   [4 4 4]
   [1 0 4]]

  [[3 3 1]
   [4 4 3]
   [0 4 4]]

  [[3 1 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [46]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1 10 11  5 16]
 [10  6  6 11  6]
 [11  6  6 42  2]
 [ 5 11 42  8  8]
 [16  6  2  8  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [47]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [48]:
ex87 = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(ex87, np.arange(0, ex87.shape[0], k), axis=0),
                                       np.arange(0, ex87.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [51]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

ex88 = np.random.randint(0,2,(50,50))
for i in range(100): ex88 = iterate(ex88)
print(ex88)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [52]:
ex89 = np.arange(10000)
np.random.shuffle(ex89)
n = 5
print (ex89[np.argpartition(-ex89,n)[:n]])


[9999 9998 9996 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [53]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [54]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [55]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.49 s ± 156 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
744 ms ± 107 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
468 ms ± 64.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [56]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [57]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 1 2]
 [0 4 3]
 [3 4 0]
 [0 3 3]
 [1 3 3]
 [1 1 4]
 [2 4 2]
 [2 2 0]
 [2 0 0]
 [2 2 2]]
[[1 1 2]
 [0 4 3]
 [3 4 0]
 [0 3 3]
 [1 3 3]
 [1 1 4]
 [2 4 2]
 [2 2 0]
 [2 0 0]]
[[1 1 2]
 [0 4 3]
 [3 4 0]
 [0 3 3]
 [1 3 3]
 [1 1 4]
 [2 4 2]
 [2 2 0]
 [2 0 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [58]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [59]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [60]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.38916606, 0.33584649, 0.46443369, 0.09823137, 0.49771457,
        0.51981558, 0.63581569, 0.18986662, 0.51694659, 0.42753494],
       [0.4620465 , 0.39874159, 0.55140976, 0.1166275 , 0.59092326,
        0.6171632 , 0.75488704, 0.22542358, 0.61375692, 0.50760086],
       [0.18239394, 0.15740418, 0.2176703 , 0.04603898, 0.23326834,
        0.24362662, 0.29799343, 0.08898649, 0.24228198, 0.20037663],
       [0.47591209, 0.41070746, 0.56795707, 0.12012738, 0.60865633,
        0.6356837 , 0.77754051, 0.23218834, 0.63217521, 0.5228335 ],
       [0.40987814, 0.35372081, 0.48915165, 0.10345941, 0.52420379,
        0.54748105, 0.66965488, 0.19997164, 0.54445936, 0.45028908],
       [0.24845197, 0.21441161, 0.29650445, 0.06271302, 0.31775167,
        0.33186143, 0.40591839, 0.12121493, 0.33002981, 0.27294749],
       [0.59567584, 0.5140624 , 0.71088402, 0.15035755, 0.76182529,
        0.79565413, 0.97320935, 0.29061876, 0.79126272, 0.65440506],
       [0.35117079, 0.30305694, 0.4190898

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [62]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [63]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [65]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17101872  0.22728179]
